# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Proyecto_TADSE/Proyecto_TADSE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE || ORIG_REF_NAME==Proyecto_TADSE}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_Circuito_para_pruebas_0_0/Proyecto_TADSE_Circuito_para_pruebas_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_Circuito_para_pruebas_0_0 || ORIG_REF_NAME==Proyecto_TADSE_Circuito_para_pruebas_0_0}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_processing_system7_0_0/Proyecto_TADSE_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_processing_system7_0_0 || ORIG_REF_NAME==Proyecto_TADSE_processing_system7_0_0}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_xadc_wiz_0_0 || ORIG_REF_NAME==Proyecto_TADSE_xadc_wiz_0_0}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_clk_wiz_0_0/Proyecto_TADSE_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_clk_wiz_0_0 || ORIG_REF_NAME==Proyecto_TADSE_clk_wiz_0_0}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_ps7_0_axi_periph_1/Proyecto_TADSE_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_ps7_0_axi_periph_1 || ORIG_REF_NAME==Proyecto_TADSE_ps7_0_axi_periph_1}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_rst_ps7_0_50M_1/Proyecto_TADSE_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_rst_ps7_0_50M_1 || ORIG_REF_NAME==Proyecto_TADSE_rst_ps7_0_50M_1}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_xbar_1/Proyecto_TADSE_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_xbar_1 || ORIG_REF_NAME==Proyecto_TADSE_xbar_1}]

# IP: bd/Proyecto_TADSE/ip/Proyecto_TADSE_auto_pc_0/Proyecto_TADSE_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Proyecto_TADSE_auto_pc_0 || ORIG_REF_NAME==Proyecto_TADSE_auto_pc_0}]

# XDC: bd/Proyecto_TADSE/Proyecto_TADSE_ooc.xdc
