# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/metastability-tool/embedded_hard/hard_v2/project_1.cache/wt [current_project]
set_property parent.project_path D:/metastability-tool/embedded_hard/hard_v2/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths d:/metastability-tool/embedded_hard/Proyecto_TADSE_IP_Custom/ip_repo/Circuito_para_pruebas_1.0 [current_project]
set_property ip_output_repo d:/metastability-tool/embedded_hard/hard_v2/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/hdl/Proyecto_TADSE_wrapper.vhd
add_files D:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/Proyecto_TADSE.bd
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_processing_system7_0_0/Proyecto_TADSE_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_clk_wiz_0_0/Proyecto_TADSE_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_clk_wiz_0_0/Proyecto_TADSE_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_clk_wiz_0_0/Proyecto_TADSE_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_rst_ps7_0_50M_1/Proyecto_TADSE_rst_ps7_0_50M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_rst_ps7_0_50M_1/Proyecto_TADSE_rst_ps7_0_50M_1.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_rst_ps7_0_50M_1/Proyecto_TADSE_rst_ps7_0_50M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xbar_1/Proyecto_TADSE_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_auto_pc_0/Proyecto_TADSE_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/Proyecto_TADSE_ooc.xdc]
set_property is_locked true [get_files D:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/Proyecto_TADSE.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Proyecto_TADSE_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef Proyecto_TADSE_wrapper.dcp

catch { report_utilization -file Proyecto_TADSE_wrapper_utilization_synth.rpt -pb Proyecto_TADSE_wrapper_utilization_synth.pb }
