# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0.xci
# IP: The module: 'Proyecto_TADSE_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_TADSE_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_TADSE_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0.xci
# IP: The module: 'Proyecto_TADSE_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_TADSE_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/metastability-tool/embedded_hard/hard_v2/project_1.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xadc_wiz_0_0/Proyecto_TADSE_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_TADSE_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
