# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/mt_hard/Zybo-Z7-Master.xdc

# Block Designs: bd/mt_hard_bd/mt_hard_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd || ORIG_REF_NAME==mt_hard_bd}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_xadc_wiz_0_0/mt_hard_bd_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_xadc_wiz_0_0 || ORIG_REF_NAME==mt_hard_bd_xadc_wiz_0_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_processing_system7_0_0/mt_hard_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_processing_system7_0_0 || ORIG_REF_NAME==mt_hard_bd_processing_system7_0_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_Circuito_para_pruebas_v1_0_0_0/mt_hard_bd_Circuito_para_pruebas_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_Circuito_para_pruebas_v1_0_0_0 || ORIG_REF_NAME==mt_hard_bd_Circuito_para_pruebas_v1_0_0_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_xlconcat_0_0/mt_hard_bd_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_xlconcat_0_0 || ORIG_REF_NAME==mt_hard_bd_xlconcat_0_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_clk_wiz_0_0/mt_hard_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_clk_wiz_0_0 || ORIG_REF_NAME==mt_hard_bd_clk_wiz_0_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_clk_wiz_0_1/mt_hard_bd_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_clk_wiz_0_1 || ORIG_REF_NAME==mt_hard_bd_clk_wiz_0_1}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_ps7_0_axi_periph_0/mt_hard_bd_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==mt_hard_bd_ps7_0_axi_periph_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_rst_ps7_0_50M_0/mt_hard_bd_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_rst_ps7_0_50M_0 || ORIG_REF_NAME==mt_hard_bd_rst_ps7_0_50M_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_xbar_0/mt_hard_bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_xbar_0 || ORIG_REF_NAME==mt_hard_bd_xbar_0}]

# IP: bd/mt_hard_bd/ip/mt_hard_bd_auto_pc_0/mt_hard_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mt_hard_bd_auto_pc_0 || ORIG_REF_NAME==mt_hard_bd_auto_pc_0}]

# XDC: bd/mt_hard_bd/mt_hard_bd_ooc.xdc
