# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/mt_TESTER/mt_TESTER.cache/wt [current_project]
set_property parent.project_path D:/mt_TESTER/mt_TESTER.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths {
  d:/Proyecto_TADSE_IP_Custom/ip_repo
  d:/Proyecto_TADSE_IP_Custom/ip_repo/Circuito_para_pruebas_1.0
} [current_project]
set_property ip_output_repo d:/mt_TESTER/mt_TESTER.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Contador_NBits.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Circuito_test.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Contador_32bits.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/DFP.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Sincronizador.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Sincroniza_RST.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Circuito_para_pruebas.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Circuito_para_pruebas_v1_0_S00_AXI.vhd
  D:/mt_TESTER/mt_TESTER.srcs/sources_1/imports/ip_repo/Circuito_para_pruebas_1.0/hdl/Circuito_para_pruebas_v1_0.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Circuito_para_pruebas_v1_0 -part xc7z020clg400-1


write_checkpoint -force -noxdef Circuito_para_pruebas_v1_0.dcp

catch { report_utilization -file Circuito_para_pruebas_v1_0_utilization_synth.rpt -pb Circuito_para_pruebas_v1_0_utilization_synth.pb }
