# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mt_hard/mt_hard.srcs/sources_1/bd/mt_hard_bd/ip/mt_hard_bd_xbar_0/mt_hard_bd_xbar_0.xci
# IP: The module: 'mt_hard_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mt_hard/mt_hard.srcs/sources_1/bd/mt_hard_bd/ip/mt_hard_bd_xbar_0/mt_hard_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mt_hard_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/mt_hard/mt_hard.srcs/sources_1/bd/mt_hard_bd/ip/mt_hard_bd_xbar_0/mt_hard_bd_xbar_0.xci
# IP: The module: 'mt_hard_bd_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mt_hard/mt_hard.srcs/sources_1/bd/mt_hard_bd/ip/mt_hard_bd_xbar_0/mt_hard_bd_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mt_hard_bd_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
