# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/metastability-tool/embedded_hard/Proyecto_TADSE_IP_Custom/Proyecto_TADSE/Proyecto_TADSE.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xbar_1/Proyecto_TADSE_xbar_1.xci
# IP: The module: 'Proyecto_TADSE_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/metastability-tool/embedded_hard/Proyecto_TADSE_IP_Custom/Proyecto_TADSE/Proyecto_TADSE.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xbar_1/Proyecto_TADSE_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_TADSE_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/metastability-tool/embedded_hard/Proyecto_TADSE_IP_Custom/Proyecto_TADSE/Proyecto_TADSE.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xbar_1/Proyecto_TADSE_xbar_1.xci
# IP: The module: 'Proyecto_TADSE_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/metastability-tool/embedded_hard/Proyecto_TADSE_IP_Custom/Proyecto_TADSE/Proyecto_TADSE.srcs/sources_1/bd/Proyecto_TADSE/ip/Proyecto_TADSE_xbar_1/Proyecto_TADSE_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Proyecto_TADSE_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
